### PR TITLE
Edit events

### PR DESCRIPTION
**Pull request by acabunoc**
Now you can edit events in the browser!

@auremoser, I got tired of editing in mongo and added this -- hope it helps! There will be bugs!

### CODE REVIEW

**Comment by acabunoc** [comment]
screen shot 2016-01-21 at 15 27 28


screen shot 2016-01-21 at 15 27 45

**Comment by stephwright** [comment]
Is this for all of us to be able to add events to the website or is this a you and @auremoser thing?

**Comment by acabunoc** [comment]
All of you can now! @stephwright 

You can't delete them yet, though.. so maybe don't play around unless I'm here to delete things for you

**Comment by stephwright** [comment]
Awesome sauce!!!  And noted... Thanks!

**Comment by auremoser** [comment]
Thanks Abby!

On Thu, Jan 21, 2016 at 4:27 PM, Stephanie Wright <notifications@github.com>
wrote:

> Awesome sauce!!! And noted... Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/site/pull/76#issuecomment-173712727>.
>



-- 
Aurelia Moser
Community Lead, Mozilla Science Lab
Twitter @auremoser | GitHub @auremoser | Skype: auremoser1

**Pull request merged**
