### PR TITLE
Add form to make events

### PR DESCRIPTION
**Pull request by acabunoc**

### CODE REVIEW

**Comment by acabunoc** [comment]
@auremoser - you made events via web interface! (can't edit yet though...)

On `/community`
screen shot 2016-01-15 at 21 41 38

Leads to `/community/new`:
screen shot 2016-01-15 at 21 42 43


You must be logged in and have the role of `staff`to access this

**Comment by auremoser** [comment]
Hooray!

**Comment by auremoser** [comment]
Love this, i was starting to add the feb 4th mixer, but want to check, at some point we can edit the details yes? I don't want to create another problem :( #neverforget

**Comment by acabunoc** [comment]
I made an issue for it! Probably won't work on it anytime soon, though. At least till after WOW probably

Also, note that it assumes event is in your current time zone!

Happy to walk you (or any contributor) through making the edit page! But I know things are busy now. We may have to settle for the Mongolab interface for a bit :)

**Comment by auremoser** [comment]
o.k. good to know! Will hold then and do it the regular way! great work,
Abby.

On Sat, Jan 16, 2016 at 9:54 AM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> I made an issue for it! Probably won't work on it anytime soon, though. At
> least till after WOW probably
>
> Also, note that it assumes event is in your current time zone!
>
> Happy to walk you (or any contributor) through making the edit page! But I
> know things are busy now. We may have to settle for the Mongolab interface
> for a bit :)
>
> > On Jan 16, 2016, at 12:04 AM, Aurelia Moser <notifications@github.com>
> wrote:
> >
> > Love this, i was starting to add the feb 4th mixer, but want to check,
> at some point we can edit the details yes? I don't want to create another
> problem :( #neverforget
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/site/pull/69#issuecomment-172213443>.
>



-- 
Aurelia Moser
Community Lead, Mozilla Science Lab
Twitter @auremoser | GitHub @auremoser | Skype: auremoser1

**Comment by acabunoc** [comment]
you can for sure *make* the event using the form! Just edit it the regular
way :)

**Pull request merged**
