### PR TITLE
added etherpad to commcall template

### PR DESCRIPTION
**Pull request by auremoser**
@acabunoc, per our convo yesterday, I tried to add a field for "notes" in both mongo and then the .jade template for community calls.

For some reason it's always defalting to the "else" statement when I run it locally, i.e. "No Notes".
```
if(ev.notes)
    h2 Notes
    p The notes can be found in 
    a(href=ev.notes)  Etherpad
else 
    h2 No Notes :( 
```
I added a notes field in the MongoDB page for Jan 14 too, and when I logged it out (there's some console log statements in the `events.js` file), it's returning the right data, so I'm not sure what's up. :(

screen shot 2015-12-23 at 10 01 58 am

Any tips?

### CODE REVIEW

**Comment by acabunoc** [comment]
Any new fields should be added to models.js
https://github.com/mozillascience/site/blob/master/models.js#L20

But also! I realized after we spoke that you can put html in the database if you escape the `"` -- see https://mozillascience.org/community-call-jan-14-11-et
```
    "description": "This month we'll be talking with the makers of citizen science apps an programs, check out <a href=\"https://public.etherpad-mozilla.org/p/sciencelab-calls-jan14-2015\">https://public.etherpad-mozilla.org/p/sciencelab-calls-jan14-2015<\/a> for more info.",
```
So it might be easier not to have a notes section!

**Comment by auremoser** [comment]
Yay, that did it :). I wanted to have a section for the etherpad stuff separate from the description, but I totally did see your note about escaping. Thanks for your help, it's ready if you're ok integrating it. Or if not, I guess I learned something so that's cool too.

**Comment by acabunoc** [comment]
A new sections sounds great :)

Can we remove the console.log statements? And should it read, "Notes can be found in *the* Etherpad"?

Happy for this to be merged once that's looked at!

**Comment by auremoser** [comment]
Done!

**Comment by acabunoc** [comment]
Should be live now!

it's alive

**Comment by auremoser** [comment]
Thank you!!

**Pull request merged**
